version: "3.2"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    links:
        - mysql
    container_name: php
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "9999:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: apache
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
      - "80:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    links:
        - mysql
    container_name: apache
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
            - data:/var/lib/mysql
            - ./dump:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - mysql:mysql
    ports:
        - 8000:80
    environment:
        MYSQL_USER: otherUser
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: rootpassword 
networks:
  frontend:
  backend:
volumes:
    data:
